from django.core.management.base import BaseCommand
from trips.models import Location, Trip, Testimonial


class Command(BaseCommand):
    help = "Seed the database with sample trips, locations, and testimonials"

    def handle(self, *args, **options):
        self._seed_locations()
        self._seed_trips()
        self._seed_testimonials()
        self.stdout.write(self.style.SUCCESS("OK Database seeded successfully!"))

    # ── Locations ─────────────────────────────────────────────────────
    def _seed_locations(self):
        data = [
            dict(
                slug="cairo", name="Cairo", order=1,
                cover_image="https://images.unsplash.com/photo-1553601538-9b57d1e92e6a?w=800&q=80",
                hero_image="https://images.unsplash.com/photo-1553601538-9b57d1e92e6a?w=1600&q=85",
                subtitle="City of a Thousand Minarets",
                description="Egypt's sprawling capital — a living city of 22 million where medieval souqs, Ottoman mosques, and world-class museums sit side by side. The Citadel, Khan el-Khalili, and the Nile felucca are unmissable.",
                long_description="Cairo is unlike anywhere on earth. The Mohamed Ali Mosque inside the Saladin Citadel looms over the city, its twin minarets and alabaster domes visible from almost everywhere. Built in the Ottoman style in the 19th century, it is one of the most beautiful mosques in the Islamic world.\n\nBeyond the Citadel, Cairo is a beautifully chaotic city where the call to prayer echoes across rooftops, tea is served at every corner, and the food is extraordinary. Wander through Khan el-Khalili's labyrinthine alleys, spend a morning at the Egyptian Museum with its 120,000 artefacts, take a felucca on the Nile at dusk, and eat koshari at a place with no menu. Cairo rewards the curious.",
                highlights=[
                    {"icon": "🕌", "label": "Citadel & Mohamed Ali Mosque", "desc": "Ottoman masterpiece with twin minarets towering over Cairo"},
                    {"icon": "🏺", "label": "Egyptian Museum",              "desc": "120,000 artefacts including Tutankhamun's gold mask"},
                    {"icon": "🛍️", "label": "Khan el-Khalili",             "desc": "Medieval bazaar with spices, jewellery and silver"},
                    {"icon": "⛵", "label": "Nile Felucca",                 "desc": "Traditional sailboat at sunset — utterly peaceful"},
                ],
                climate="Hot desert. Best Oct–Apr.",
                best_time="October – April",
                language="Arabic (English widely spoken)",
                currency="Egyptian Pound (EGP)",
                timezone="UTC+2 (EET)",
            ),
            dict(
                slug="giza", name="Giza", order=2,
                cover_image="https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80",
                hero_image="https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=1600&q=85",
                subtitle="Home of the Last Ancient Wonder",
                description="The Giza Plateau is home to the Great Pyramid, the Sphinx, and the pyramid fields of Saqqara — the last surviving Wonder of the Ancient World and one of the most breathtaking sights on earth.",
                long_description="Standing at the base of the Great Pyramid and realising you are looking at something built 4,500 years ago is genuinely humbling. The scale is impossible to convey in photographs: each stone block weighs up to 80 tonnes, and the pyramid was the tallest man-made structure on earth for nearly 4,000 years.\n\nThe Giza Plateau holds three great pyramids — Khufu, Khafre and Menkaure — along with the Great Sphinx, which has kept watch over the desert for 4,500 years. Nearby Saqqara contains the Step Pyramid, the world's oldest stone structure, and the vast necropolis of Memphis. You can descend into a pyramid, ride a camel across the plateau, and watch the Sound & Light Show after dark.",
                highlights=[
                    {"icon": "🏛️", "label": "Great Pyramid of Khufu",  "desc": "The last of the Seven Wonders of the Ancient World"},
                    {"icon": "🦁", "label": "Great Sphinx",            "desc": "4,500-year-old guardian carved from a single limestone outcrop"},
                    {"icon": "🏺", "label": "Saqqara & Step Pyramid",  "desc": "The world's oldest stone structure, 20 minutes from Giza"},
                    {"icon": "🐪", "label": "Camel Ride",              "desc": "Classic plateau ride with panoramic pyramid views"},
                ],
                climate="Hot desert. Best Oct–Apr.",
                best_time="October – April",
                language="Arabic (English widely spoken)",
                currency="Egyptian Pound (EGP)",
                timezone="UTC+2 (EET)",
            ),
            dict(
                slug="luxor", name="Luxor", order=3,
                cover_image="https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
                hero_image="https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1600&q=85",
                subtitle="World's Greatest Open-Air Museum",
                description="Ancient Thebes — once the most powerful city on earth. The Valley of the Kings, Karnak temple, and the banks of the Nile are unmatched anywhere.",
                long_description="Luxor is where Egyptian history becomes overwhelming in the best possible way. The East Bank holds the colossal Karnak temple complex — a city within a city, built and expanded over 2,000 years — and the elegant Luxor Temple illuminated at night. Cross the Nile to the West Bank and you enter the realm of the dead: the Valley of the Kings, Hatshepsut's mortuary temple, and the enigmatic Colossi of Memnon.\n\nUnlike Cairo, Luxor is small and navigable. You can cycle between sites. The pace is slower, the light is golden, and everywhere you turn there is something that shouldn't exist.",
                highlights=[
                    {"icon": "👑", "label": "Valley of the Kings", "desc": "Tomb of Tutankhamun and 62 royal burial chambers"},
                    {"icon": "🏛️", "label": "Karnak Temple",       "desc": "The largest religious complex ever built"},
                    {"icon": "🌅", "label": "Hot Air Balloon",      "desc": "Sunrise over the Theban hills — unmissable"},
                    {"icon": "🚢", "label": "Nile Cruise",          "desc": "Classic 3–7 night cruise between Luxor and Aswan"},
                ],
                climate="Very hot summers. Best Nov–Mar.",
                best_time="November – March",
                language="Arabic (English at tourist sites)",
                currency="Egyptian Pound (EGP)",
                timezone="UTC+2 (EET)",
            ),
            dict(
                slug="aswan", name="Aswan", order=4,
                cover_image="https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&q=80",
                hero_image="https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=1600&q=85",
                subtitle="Gateway to Nubia",
                description="Egypt's most tranquil city. Sailboats on the Nile, ancient Nubian villages, the Abu Simbel temples, and the best sunsets in Africa.",
                long_description="Aswan is the most serene city in Egypt — and the most visually beautiful. The Nile here is studded with granite boulders and green islands. Nubian villages paint their houses in vivid colour. The light in the late afternoon turns everything to amber.\n\nThe town itself is manageable on foot. The souk is relaxed and friendly. And nearby: Philae Temple (moved stone by stone to save it from the Nile), the unfinished obelisk still lying in its quarry, and — most dramatically — Abu Simbel, a day trip away by flight.",
                highlights=[
                    {"icon": "🏺", "label": "Abu Simbel",      "desc": "Ramesses II's twin temples — a UNESCO masterpiece"},
                    {"icon": "⛵", "label": "Felucca Sailing",  "desc": "Drift past Elephantine Island at sunset with tea"},
                    {"icon": "🎨", "label": "Nubian Village",   "desc": "Crocodile shrines, painted houses, warm hospitality"},
                    {"icon": "🏛️", "label": "Philae Temple",   "desc": "Dedicated to Isis, relocated to save it from flooding"},
                ],
                climate="Warm year-round. Peak Nov–Feb.",
                best_time="October – April",
                language="Arabic / Nubian (English at sites)",
                currency="Egyptian Pound (EGP)",
                timezone="UTC+2 (EET)",
            ),
            dict(
                slug="alexandria", name="Alexandria", order=5,
                cover_image="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
                hero_image="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=85",
                subtitle="Pearl of the Mediterranean",
                description="Founded by Alexander the Great, this Mediterranean jewel has ancient catacombs, a legendary library, fresh seafood, and a breezy seaside atmosphere unlike anywhere else in Egypt.",
                long_description="Alexandria was once the greatest city in the world. Founded by Alexander the Great in 331 BC, home to the ancient Library of Alexandria, the Pharos lighthouse, and Cleopatra, it drew scholars and traders from across the known world.\n\nToday it is Egypt's second city and its most Mediterranean. The corniche runs for miles along the sea. The seafood is legendary. The atmosphere — looser, cooler, more European — is unlike anywhere else in the country. The Bibliotheca Alexandrina is a marvel of modern architecture housing 8 million books. The Catacombs of Kom el Shoqafa are the largest Roman burial site in Egypt.",
                highlights=[
                    {"icon": "📚", "label": "Bibliotheca Alexandrina", "desc": "8 million books, stunning architecture, great cafe"},
                    {"icon": "🏰", "label": "Qaitbay Citadel",         "desc": "15th-century fortress on the site of the ancient Pharos"},
                    {"icon": "🏺", "label": "Catacombs",               "desc": "Kom el Shoqafa — largest Roman necropolis in Egypt"},
                    {"icon": "🦞", "label": "Seafood",                 "desc": "The freshest fish in Egypt, right on the corniche"},
                ],
                climate="Mediterranean. Mild year-round.",
                best_time="March – June, Sep – Nov",
                language="Arabic (some French/English)",
                currency="Egyptian Pound (EGP)",
                timezone="UTC+2 (EET)",
            ),
            dict(
                slug="hurghada", name="Hurghada", order=6,
                cover_image="https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
                hero_image="https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&q=85",
                subtitle="Red Sea Riviera",
                description="World-class diving and snorkelling in some of the clearest, most colourful waters on the planet — plus desert safaris and vibrant nightlife.",
                long_description="Hurghada is Egypt's resort capital, and for good reason: the Red Sea here is extraordinary. The coral reefs are among the healthiest on earth, visibility reaches 30 metres, and the marine life — mantas, dolphins, whale sharks — is spectacular.\n\nBeyond the water, desert safaris take you into the Sahara at sunset. The old town (Ad-Dahar) has a more local feel with small restaurants and markets. And for those who want nothing but sun, sea, and silence — the islands offshore are among the most beautiful anywhere.",
                highlights=[
                    {"icon": "🤿", "label": "Diving",          "desc": "30m visibility, mantas, and coral gardens"},
                    {"icon": "🐬", "label": "Dolphin House",   "desc": "Swim with wild spinner dolphins in the open sea"},
                    {"icon": "🏜️", "label": "Desert Safari",  "desc": "Quad bikes, Bedouin camps, and Sahara sunsets"},
                    {"icon": "🏝️", "label": "Giftun Islands", "desc": "Pristine white beaches, 30 min by boat"},
                ],
                climate="Year-round sunshine. Best Oct–May.",
                best_time="Year-round (avoid Jul–Aug heat)",
                language="Arabic (English at resorts)",
                currency="Egyptian Pound (EGP)",
                timezone="UTC+2 (EET)",
            ),
            dict(
                slug="sinai", name="Sinai", order=7,
                cover_image="https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&q=80",
                hero_image="https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1600&q=85",
                subtitle="Mountains Meet the Sea",
                description="Dahab's turquoise bays, the legendary Blue Hole dive site, Mount Sinai at sunrise, and the ancient St. Catherine's Monastery.",
                long_description="Sinai occupies a unique place in human history and geography. The mountains are among the oldest exposed rock on earth. The sea is turquoise and calm. Bedouin tribes have lived here for thousands of years.\n\nDahab is a relaxed beach town — part diving mecca, part backpacker haven — with the world-famous Blue Hole dive site just minutes away. The drive to Mount Sinai takes you through dramatic desert landscapes to one of the world's great sunrise experiences. And St. Catherine's Monastery, still active after 1,500 years, is extraordinary.",
                highlights=[
                    {"icon": "🌊", "label": "Blue Hole Dahab",   "desc": "World-famous dive site — stunning for snorkellers too"},
                    {"icon": "⛰️", "label": "Mount Sinai",       "desc": "2 hours up, sunrise at the summit, unforgettable"},
                    {"icon": "🕌", "label": "St. Catherine's",   "desc": "1,500-year-old monastery — active and remarkable"},
                    {"icon": "🏞️", "label": "Ras Mohammed",     "desc": "National park with the best reef diving in the Sinai"},
                ],
                climate="Desert. Sea breezes on coast.",
                best_time="October – April",
                language="Arabic / Bedouin dialects (English in Dahab)",
                currency="Egyptian Pound (EGP)",
                timezone="UTC+2 (EET)",
            ),
            dict(
                slug="siwa", name="Siwa Oasis", order=8,
                cover_image="https://images.unsplash.com/photo-1527736947477-2790e28f3443?w=800&q=80",
                hero_image="https://images.unsplash.com/photo-1527736947477-2790e28f3443?w=1600&q=85",
                subtitle="Egypt's Most Remote Paradise",
                description="A verdant oasis deep in the Sahara, famous for the Oracle Temple where Alexander the Great was declared a god, salt lakes, ancient Berber culture, and the Great Sand Sea.",
                long_description="Siwa Oasis sits in a great depression in the western Sahara, 50 kilometres from the Libyan border. It is one of Egypt's most remote and most extraordinary places — an island of date palms and olive trees floating in a sea of golden dunes.\n\nFor centuries, Siwa was ruled by its own Berber Siwi people, with a distinct language and culture unlike anywhere else in Egypt. Alexander the Great made the journey here in 331 BC to consult the Oracle of Amun, who declared him the son of Zeus. The ruins of that oracle temple still stand.\n\nToday Siwa is known for its salt lakes (where you float effortlessly), the Great Sand Sea (where dunes reach 100 metres), the medieval mud-brick fortress of Shali, and the extraordinary silence that comes with true desert remoteness.",
                highlights=[
                    {"icon": "🏛️", "label": "Oracle Temple of Amun", "desc": "Where Alexander the Great was declared a god in 331 BC"},
                    {"icon": "🌊", "label": "Salt Lakes",             "desc": "Float effortlessly in Siwa's hypersaline lakes"},
                    {"icon": "🏜️", "label": "Great Sand Sea",        "desc": "100-metre dunes — the most dramatic in the Sahara"},
                    {"icon": "🏰", "label": "Shali Fortress",        "desc": "Medieval mud-brick town rising from the oasis floor"},
                ],
                climate="Hot desert. Very cold winter nights.",
                best_time="October – April",
                language="Siwi Berber / Arabic (basic English at hotels)",
                currency="Egyptian Pound (EGP)",
                timezone="UTC+2 (EET)",
            ),
        ]
        for d in data:
            Location.objects.update_or_create(
                slug=d["slug"],
                defaults={**d, "country": "Egypt", "country_code": "EG"},
            )
        self.stdout.write("  OK Locations (8)")

    # ── Trips ──────────────────────────────────────────────────────────
    def _seed_trips(self):
        cairo      = Location.objects.get(slug="cairo")
        giza       = Location.objects.get(slug="giza")
        luxor      = Location.objects.get(slug="luxor")
        aswan      = Location.objects.get(slug="aswan")
        sinai      = Location.objects.get(slug="sinai")
        alexandria = Location.objects.get(slug="alexandria")
        siwa       = Location.objects.get(slug="siwa")

        trips = [
            # ── Giza ──
            dict(
                slug="pyramids-sphinx-full-day", type="tour", location=giza,
                title="Pyramids, Sphinx & Egyptian Museum Full-Day Tour",
                tagline="The ultimate Giza classic",
                description="Walk the Giza Plateau with a licensed Egyptologist, descend into a pyramid, meet the Sphinx up close, then explore 120,000 artefacts at the Egyptian Museum.",
                cover_image="https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80",
                price=49, price_currency="USD", price_unit="per_person", original_price=65,
                rating=4.9, review_count=312, duration_label="8 hours", duration_hours=8,
                languages=["en", "ar"], max_group_size=12,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=True,
                highlights=["Licensed Egyptologist guide", "Private vehicle pickup", "Entry tickets included"],
                includes=["Hotel pickup & drop-off", "All entry tickets", "Bottled water", "Expert guide"],
                excludes=["Lunch", "Tips & gratuities", "Camel rides"],
            ),
            dict(
                slug="saqqara-memphis-day-trip", type="tour", location=giza,
                title="Saqqara Step Pyramid & Memphis Day Trip",
                tagline="Older than Giza",
                description="Explore the world's oldest stone structure at Saqqara and the ancient capital of Memphis with its colossal Ramesses II statue.",
                cover_image="https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
                price=42, price_currency="USD", price_unit="per_person",
                rating=4.8, review_count=98, duration_label="6 hours", duration_hours=6,
                languages=["en", "ar"], max_group_size=12,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=False,
                highlights=["Step Pyramid of Djoser", "Colossal Ramesses II statue", "Licensed Egyptologist"],
                includes=["Hotel pickup", "Entry tickets", "Licensed guide", "Water"],
                excludes=["Lunch", "Tips"],
            ),
            # ── Cairo ──
            dict(
                slug="egyptian-cooking-class", type="experience", location=cairo,
                title="Egyptian Home Cooking & Food Tasting with a Local Family",
                tagline="A feast you won't forget",
                description="Learn to cook koshari, ful medames and mahshi in a Cairene home.",
                cover_image="https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
                price=38, price_currency="USD", price_unit="per_person",
                rating=5.0, review_count=87, duration_label="4 hours", duration_hours=4,
                languages=["en", "ar"], max_group_size=8,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=False, is_featured=True,
                highlights=["Cook in a real Egyptian home", "3-course meal included", "Take home recipes"],
                includes=["All ingredients", "Full meal", "Recipe card"],
                excludes=["Hotel transfer"],
            ),
            dict(
                slug="cairo-airport-transfer", type="transfer", location=cairo,
                title="Cairo International Airport to City Centre Private Transfer",
                tagline="Stress-free arrival",
                description="Private, air-conditioned vehicle direct to your hotel — flight tracking included.",
                cover_image="https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80",
                price=22, price_currency="USD", price_unit="per_vehicle",
                rating=4.8, review_count=541, duration_label="45 min", duration_hours=1,
                languages=["en", "ar"],
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=False,
                highlights=["Flight tracking", "Professional driver", "Air-conditioned vehicle"],
                includes=["Meet & greet", "Luggage assistance", "All tolls"],
                excludes=["Tips"],
            ),
            dict(
                slug="cairo-night-transfer", type="transfer", location=cairo,
                title="Cairo City Centre to Cairo Airport Night Transfer",
                tagline="Never miss a flight",
                description="Reliable late-night pickup with professional driver and luggage assistance.",
                cover_image="https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80",
                price=22, price_currency="USD", price_unit="per_vehicle",
                rating=4.7, review_count=289, duration_label="50 min", duration_hours=1,
                languages=["en", "ar"],
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=False,
                highlights=["24/7 availability", "Flight monitoring", "Luggage help"],
                includes=["Door-to-door pickup", "All tolls"],
                excludes=["Tips"],
            ),
            dict(
                slug="khan-el-khalili-walk", type="experience", location=cairo,
                title="Khan el-Khalili Bazaar Night Walk & Mint Tea",
                tagline="Cairo's medieval heart",
                description="Wind through the labyrinthine medieval souq, meet artisans and sip mint tea at the oldest cafe in the world.",
                cover_image="https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
                price=32, price_currency="USD", price_unit="per_person",
                rating=4.8, review_count=124, duration_label="3 hours", duration_hours=3,
                languages=["en", "ar"], max_group_size=10,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=False, is_featured=False,
                highlights=["700-year-old bazaar", "Mint tea at El-Fishawy", "Local artisans"],
                includes=["Mint tea", "Local guide"],
                excludes=["Shopping", "Transport"],
            ),
            dict(
                slug="calligraphy-workshop-cairo", type="experience", location=cairo,
                title="Arabic Calligraphy Workshop in Old Cairo",
                tagline="Write your name in history",
                description="A master calligrapher teaches you the art of Arabic script in a 500-year-old caravanserai.",
                cover_image="https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
                price=45, price_currency="USD", price_unit="per_person",
                rating=4.9, review_count=43, duration_label="2.5 hours", duration_hours=3,
                languages=["en", "ar"], max_group_size=6,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=False, is_featured=False,
                highlights=["Master calligrapher", "500-year-old caravanserai", "Keep your artwork"],
                includes=["All materials", "Tea", "Artwork to take home"],
                excludes=["Transport"],
            ),
            # ── Luxor ──
            dict(
                slug="luxor-valley-of-kings", type="tour", location=luxor,
                title="Valley of the Kings, Karnak & Luxor Temple Day Tour",
                tagline="Ancient Thebes in one day",
                description="Visit the tomb of Tutankhamun, the colossal Karnak temple complex and riverside Luxor Temple at dusk.",
                cover_image="https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
                price=75, price_currency="USD", price_unit="per_person",
                rating=4.8, review_count=203, duration_label="Full day", duration_hours=10,
                languages=["en", "ar", "de"], max_group_size=14,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=True,
                highlights=["Tomb of Tutankhamun", "Karnak temple light show", "Dusk at Luxor Temple"],
                includes=["Hotel pickup", "Entry tickets", "Licensed guide", "Lunch"],
                excludes=["Personal expenses", "Tips"],
            ),
            dict(
                slug="luxor-hotel-transfer", type="transfer", location=luxor,
                title="Luxor Airport to East Bank Hotel Private Transfer",
                tagline="Arrive in style",
                description="Climate-controlled private car from Luxor Airport to any East Bank hotel.",
                cover_image="https://images.unsplash.com/photo-1485463611174-f302f6a5c1c9?w=800&q=80",
                price=18, price_currency="USD", price_unit="per_vehicle",
                rating=4.9, review_count=198, duration_label="25 min", duration_hours=1,
                languages=["en", "ar"],
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=False,
                highlights=["Private vehicle", "Air-conditioned", "All East Bank hotels"],
                includes=["Meet & greet", "Luggage help", "All tolls"],
                excludes=["Tips"],
            ),
            # ── Aswan ──
            dict(
                slug="nile-felucca-sunset", type="experience", location=aswan,
                title="Sunset Felucca Sail on the Nile with Tea & Snacks",
                tagline="Magic on the water",
                description="Drift along the Nile as the sun dips behind the desert hills. Traditional tea and snacks included.",
                cover_image="https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&q=80",
                price=28, price_currency="USD", price_unit="per_person",
                rating=4.9, review_count=156, duration_label="2 hours", duration_hours=2,
                languages=["en", "ar"], max_group_size=10,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=False, is_featured=True,
                highlights=["Golden-hour Nile views", "Traditional tea & snacks", "Small group"],
                includes=["Traditional tea", "Light snacks", "Life jackets"],
                excludes=["Hotel pickup"],
            ),
            dict(
                slug="abu-simbel-day-trip", type="tour", location=aswan,
                title="Abu Simbel Temples Day Trip from Aswan by Flight",
                tagline="Ramesses II awaits",
                description="Fly to Abu Simbel and witness the most dramatic twin temples in Egypt.",
                cover_image="https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&q=80",
                price=185, price_currency="USD", price_unit="per_person",
                rating=4.9, review_count=94, duration_label="Full day", duration_hours=9,
                languages=["en", "ar"], max_group_size=12,
                cancellation_policy="partial_refund", instant_confirmation=False,
                pickup_included=True, is_featured=True,
                highlights=["Fly over the Sahara", "Ramesses II & Nefertari temples", "Expert Egyptologist"],
                includes=["Return flights", "Entry tickets", "Licensed guide", "Hotel pickup"],
                excludes=["Meals", "Personal expenses"],
            ),
            # ── Sinai ──
            dict(
                slug="dahab-snorkel-day", type="tour", location=sinai,
                title="Dahab Blue Hole Snorkelling & Canyon Adventure",
                tagline="Red Sea magic",
                description="Snorkel the world-famous Blue Hole reef, then explore the canyon and lagoon with a certified instructor.",
                cover_image="https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
                price=55, price_currency="USD", price_unit="per_person",
                rating=4.7, review_count=67, duration_label="6 hours", duration_hours=6,
                languages=["en", "ar"], max_group_size=8,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=False,
                highlights=["Blue Hole reef", "Canyon snorkelling", "Certified instructor"],
                includes=["Snorkel equipment", "Instructor", "Hotel pickup", "Lunch"],
                excludes=["Wetsuit rental"],
            ),
            # ── Alexandria ──
            dict(
                slug="alexandria-day-trip", type="tour", location=alexandria,
                title="Alexandria Day Trip - Library, Catacombs & Qaitbay",
                tagline="Pearl of the Mediterranean",
                description="Journey to Alexandria: visit the Bibliotheca Alexandrina, the Catacombs of Kom el Shoqafa, and the 15th-century Qaitbay Citadel on the sea.",
                cover_image="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
                price=89, price_currency="USD", price_unit="per_person",
                rating=4.7, review_count=118, duration_label="Full day", duration_hours=11,
                languages=["en", "ar"], max_group_size=14,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=False,
                highlights=["Bibliotheca Alexandrina", "Roman catacombs", "Qaitbay sea citadel"],
                includes=["Cairo pickup", "Entry tickets", "Lunch", "Licensed guide"],
                excludes=["Personal expenses", "Tips"],
            ),
            # ── Siwa ──
            dict(
                slug="siwa-oasis-explorer", type="tour", location=siwa,
                title="Siwa Oasis Explorer — Oracle Temple, Salt Lakes & Dunes",
                tagline="Egypt's last great secret",
                description="A full-day journey through Siwa: the Oracle Temple of Amun, float in the salt lakes, and watch the sunset from a 100-metre sand dune in the Great Sand Sea.",
                cover_image="https://images.unsplash.com/photo-1527736947477-2790e28f3443?w=800&q=80",
                price=68, price_currency="USD", price_unit="per_person",
                rating=4.9, review_count=52, duration_label="Full day", duration_hours=10,
                languages=["en", "ar"], max_group_size=10,
                cancellation_policy="free_cancellation", instant_confirmation=True,
                pickup_included=True, is_featured=True,
                highlights=["Oracle Temple of Amun", "Salt lake float", "Great Sand Sea sunset"],
                includes=["4x4 transport", "Local guide", "Lunch at oasis restaurant", "Entry tickets"],
                excludes=["Personal expenses", "Tips"],
            ),
            dict(
                slug="siwa-desert-camp", type="experience", location=siwa,
                title="Siwa Desert Camp — Overnight in the Great Sand Sea",
                tagline="Sleep under a billion stars",
                description="Camp overnight in the Great Sand Sea, enjoy a Bedouin dinner, stargaze in absolute darkness, and wake to sunrise over the dunes.",
                cover_image="https://images.unsplash.com/photo-1517826759941-0d9a9bdf9e59?w=800&q=80",
                price=120, price_currency="USD", price_unit="per_person",
                rating=5.0, review_count=31, duration_label="Overnight", duration_hours=18,
                languages=["en", "ar"], max_group_size=8,
                cancellation_policy="partial_refund", instant_confirmation=False,
                pickup_included=True, is_featured=True,
                highlights=["Overnight desert camp", "Bedouin dinner under stars", "Sunrise dune walk"],
                includes=["4x4 transport", "Tent & sleeping bag", "Dinner & breakfast", "Guide"],
                excludes=["Personal expenses", "Alcoholic drinks"],
            ),
        ]

        for t in trips:
            slug = t["slug"]
            Trip.objects.update_or_create(slug=slug, defaults=t)

        self.stdout.write("  OK Trips (15)")

    # ── Testimonials ───────────────────────────────────────────────────
    def _seed_testimonials(self):
        data = [
            dict(
                name="Sarah Mitchell", country="United Kingdom",
                avatar="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
                rating=5, trip_name="Pyramids & Sphinx Full-Day Tour", date="March 2026",
                body="Absolutely phenomenal experience. Our guide Ahmed was a walking encyclopedia — his passion for Egyptology was infectious. The private vehicle pickup was seamless, and the pacing of the day was perfect. This is the only way to see the Pyramids.",
                order=1,
            ),
            dict(
                name="Thomas Brenner", country="Germany",
                avatar="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
                rating=5, trip_name="Luxor Valley of the Kings Tour", date="February 2026",
                body="We did two tours through TriVox and both exceeded expectations. The booking was instant, the price was transparent, and our guide was genuinely wonderful. Luxor felt like a dream — I had no idea Egyptian history ran so deep.",
                order=2,
            ),
            dict(
                name="Yuki Tanaka", country="Japan",
                avatar="https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
                rating=5, trip_name="Egyptian Home Cooking Experience", date="March 2026",
                body="Cooking with Fatima's family was the highlight of my entire Egypt trip — more memorable than any monument. We made ful medames, koshari, and mahshi from scratch. The laughter, the warmth, the food — I will never forget it.",
                order=3,
            ),
            dict(
                name="Marco Rossi", country="Italy",
                avatar="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
                rating=5, trip_name="Nile Felucca Sunset Sail", date="January 2026",
                body="The felucca at sunset in Aswan is pure magic. No engine noise, just wind and water and the sound of the Nile. Our captain was jovial and knowledgeable. Twenty euros for the most peaceful hour of my life.",
                order=4,
            ),
        ]
        for d in data:
            Testimonial.objects.update_or_create(name=d["name"], trip_name=d["trip_name"], defaults=d)
        self.stdout.write("  OK Testimonials (4)")
