import type { Booking, User } from "@/types";

export const MOCK_USER: User = {
  id:             1,
  email:          "sarah.mitchell@example.com",
  first_name:     "Sarah",
  last_name:      "Mitchell",
  avatar:         "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
  phone:          "+44 7700 900123",
  nationality:    "British",
  date_joined:    "2024-08-15T00:00:00Z",
  bookings_count: 4,
};

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 1,
    reference: "RH-2026-000312",
    status: "confirmed",
    trip: {
      id: 1, slug: "pyramids-sphinx-full-day", type: "tour",
      title: "Pyramids, Sphinx & Egyptian Museum Full-Day Tour",
      tagline: "The ultimate Cairo classic",
      description: "",
      cover_image: "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80",
      gallery: [],
      location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
      categories: [], price: 49, price_currency: "USD", price_unit: "per_person",
      rating: 4.9, review_count: 312, duration_label: "8 hours",
      languages: ["en"], cancellation_policy: "free_cancellation",
      instant_confirmation: true, pickup_included: true,
      is_featured: true, is_active: true,
      highlights: [], includes: [], excludes: [],
      created_at: "", updated_at: "",
    },
    date: "2026-05-15",
    time: "08:00",
    participants: [
      { type: "adult",  count: 2, price: 49 },
      { type: "child",  count: 1, price: 35 },
    ],
    addons: [
      {
        addon: {
          id: 1, slug: "audio-guide", name: "Personal audio guide",
          description: "Wireless earpiece tour commentary",
          price: 8, price_currency: "USD", price_unit: "per_person",
          is_required: false, category: "guide",
        },
        quantity: 2, subtotal: 16,
      },
    ],
    summary: {
      trip_subtotal: 133, addons_subtotal: 16, taxes: 7.45, total: 156.45, currency: "USD",
    },
    created_at: "2026-04-01T10:23:00Z",
    updated_at: "2026-04-01T10:23:00Z",
    confirmation_sent: true,
    first_name: "Sarah", last_name: "Mitchell",
    email: "sarah.mitchell@example.com", phone: "+44 7700 900123",
  },
  {
    id: 2,
    reference: "RH-2026-000287",
    status: "completed",
    trip: {
      id: 2, slug: "egyptian-cooking-class", type: "experience",
      title: "Egyptian Home Cooking & Food Tasting",
      tagline: "A feast you won't forget",
      description: "",
      cover_image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
      gallery: [],
      location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
      categories: [], price: 38, price_currency: "USD", price_unit: "per_person",
      rating: 5.0, review_count: 87, duration_label: "4 hours",
      languages: ["en"], cancellation_policy: "free_cancellation",
      instant_confirmation: true, pickup_included: false,
      is_featured: true, is_active: true,
      highlights: [], includes: [], excludes: [],
      created_at: "", updated_at: "",
    },
    date: "2026-03-20",
    participants: [{ type: "adult", count: 2, price: 38 }],
    addons: [],
    summary: { trip_subtotal: 76, addons_subtotal: 0, taxes: 3.80, total: 79.80, currency: "USD" },
    created_at: "2026-02-14T09:12:00Z",
    updated_at: "2026-03-20T14:00:00Z",
    confirmation_sent: true,
    first_name: "Sarah", last_name: "Mitchell",
    email: "sarah.mitchell@example.com", phone: "+44 7700 900123",
  },
  {
    id: 3,
    reference: "RH-2026-000198",
    status: "confirmed",
    trip: {
      id: 4, slug: "cairo-airport-transfer", type: "transfer",
      title: "Cairo Airport → City Centre Private Transfer",
      tagline: "Stress-free arrival",
      description: "",
      cover_image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80",
      gallery: [],
      location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
      categories: [], price: 22, price_currency: "USD", price_unit: "per_vehicle",
      rating: 4.8, review_count: 541, duration_label: "45 min",
      languages: ["en"], cancellation_policy: "free_cancellation",
      instant_confirmation: true, pickup_included: true,
      is_featured: false, is_active: true,
      highlights: [], includes: [], excludes: [],
      created_at: "", updated_at: "",
    },
    date: "2026-05-14",
    time: "14:30",
    participants: [{ type: "adult", count: 1, price: 22 }],
    addons: [],
    summary: { trip_subtotal: 22, addons_subtotal: 0, taxes: 1.10, total: 23.10, currency: "USD" },
    created_at: "2026-04-01T10:25:00Z",
    updated_at: "2026-04-01T10:25:00Z",
    confirmation_sent: true,
    first_name: "Sarah", last_name: "Mitchell",
    email: "sarah.mitchell@example.com", phone: "+44 7700 900123",
  },
  {
    id: 4,
    reference: "RH-2025-000891",
    status: "cancelled",
    trip: {
      id: 3, slug: "luxor-valley-of-kings", type: "tour",
      title: "Valley of the Kings, Karnak & Luxor Temple Day Tour",
      tagline: "Ancient Thebes in one day",
      description: "",
      cover_image: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
      gallery: [],
      location: { id: 2, name: "Luxor", slug: "luxor", country: "Egypt", country_code: "EG" },
      categories: [], price: 75, price_currency: "USD", price_unit: "per_person",
      rating: 4.8, review_count: 203, duration_label: "Full day",
      languages: ["en"], cancellation_policy: "free_cancellation",
      instant_confirmation: true, pickup_included: true,
      is_featured: true, is_active: true,
      highlights: [], includes: [], excludes: [],
      created_at: "", updated_at: "",
    },
    date: "2025-12-10",
    participants: [{ type: "adult", count: 2, price: 75 }],
    addons: [],
    summary: { trip_subtotal: 150, addons_subtotal: 0, taxes: 7.50, total: 157.50, currency: "USD" },
    created_at: "2025-11-20T08:00:00Z",
    updated_at: "2025-11-28T11:30:00Z",
    confirmation_sent: false,
    first_name: "Sarah", last_name: "Mitchell",
    email: "sarah.mitchell@example.com", phone: "+44 7700 900123",
    notes: "Cancelled due to travel change",
  },
];
