import type { Tour, Transfer, Experience } from "@/types";

export const MOCK_TOUR: Tour = {
  id: 1, slug: "pyramids-sphinx-full-day", type: "tour",
  title: "Pyramids, Sphinx & Egyptian Museum Full-Day Tour",
  tagline: "The ultimate Cairo classic — history, wonder, and local insight in one day",
  description: "Step back 4,500 years and stand at the base of the last surviving Wonder of the Ancient World. This full-day private tour with a licensed Egyptologist takes you through the Giza Plateau, inside a pyramid, face-to-face with the Great Sphinx, and then deep into the treasure-filled halls of the Egyptian Museum. Lunch at a local restaurant with a view of the Nile is included.\n\nYour guide will bring these ancient stories to life, sharing the latest archaeological discoveries and the human stories behind the monuments. This is not a rushed group tour — your pace, your questions, your experience.",
  cover_image: "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=1600&q=85",
  gallery: [
    { id: 1, url: "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=1200&q=80", alt_text: "Pyramids of Giza", type: "image", is_cover: true, order: 0 },
    { id: 2, url: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",  alt_text: "Sphinx closeup",  type: "image", is_cover: false, order: 1 },
    { id: 3, url: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&q=80",  alt_text: "Inside a pyramid", type: "image", is_cover: false, order: 2 },
    { id: 4, url: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80", alt_text: "Egyptian Museum",  type: "image", is_cover: false, order: 3 },
    { id: 5, url: "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&q=80",   alt_text: "Nile view",        type: "image", is_cover: false, order: 4 },
  ],
  location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
  categories: [{ id: 1, name: "History & Culture", slug: "history-culture" }],
  price: 49, price_currency: "USD", price_unit: "per_person", original_price: 65,
  rating: 4.9, review_count: 312,
  review_stats: { average: 4.9, total: 312, distribution: { 5: 261, 4: 38, 3: 8, 2: 3, 1: 2 } },
  duration_label: "8 hours", duration_hours: 8,
  languages: ["English", "Arabic", "French"],
  max_group_size: 12, min_age: 5,
  cancellation_policy: "free_cancellation", cancellation_hours: 24,
  instant_confirmation: true, pickup_included: true,
  is_featured: true, is_active: true,
  highlights: [
    "Stand inside the Great Pyramid of Khufu",
    "Private licensed Egyptologist guide",
    "Face-to-face with the Great Sphinx",
    "120,000 artefacts at the Egyptian Museum",
    "Lunch with Nile views included",
    "Hotel pickup and drop-off",
  ],
  includes: ["Private transport", "Egyptologist guide", "Pyramid entry tickets", "Egyptian Museum tickets", "Nile-view lunch", "Bottled water"],
  excludes: ["Gratuities (optional)", "Personal purchases", "Camel/horse rides (available on-site)"],
  addons: [
    { id: 1, slug: "audio-guide", name: "Personal audio guide", description: "Wireless earpiece tour commentary in your language", price: 8, price_currency: "USD", price_unit: "per_person", is_required: false, category: "guide", max_quantity: 10 },
    { id: 2, slug: "camel-ride",  name: "Camel ride at Giza",   description: "20-minute guided camel ride on the Giza plateau",  price: 15, price_currency: "USD", price_unit: "per_person", is_required: false, category: "equipment", max_quantity: 4 },
    { id: 3, slug: "photo-pack",  name: "Professional photo session", description: "30-minute photoshoot with a local photographer",    price: 35, price_currency: "USD", price_unit: "fixed",      is_required: false, category: "photo" },
  ],
  difficulty: "easy",
  start_location: "Your hotel (Cairo / Giza)", end_location: "Your hotel",
  meeting_point: "Hotel lobby",
  guide_name: "Ahmed Hassan", guide_bio: "Licensed Egyptologist with 12 years of experience. MSc in Archaeology from Cairo University. Ahmed has guided everyone from backpackers to heads of state and genuinely loves sharing Egypt's stories.",
  guide_avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
  itinerary: [
    {
      day: 1, title: "The Giza Plateau & Egyptian Museum",
      stops: [
        { order: 1, time: "08:00 AM", title: "Hotel pickup",             description: "Private vehicle collects you from your hotel lobby.",                                              type: "transport", duration: "30 min" },
        { order: 2, time: "08:30 AM", title: "Great Pyramid of Khufu",   description: "Enter the oldest and largest of the three Giza pyramids. Your guide explains its construction mysteries.", type: "activity", duration: "1.5 hrs",  location: "Giza Plateau" },
        { order: 3, time: "10:00 AM", title: "Pyramid of Khafre & Menkaure", description: "Explore the second and third pyramids, with stunning views across the plateau.",               type: "activity", duration: "45 min" },
        { order: 4, time: "10:45 AM", title: "The Great Sphinx",         description: "Stand at the base of the enigmatic limestone colossus and hear its 4,500-year history.",           type: "activity", duration: "30 min",  location: "Giza Plateau" },
        { order: 5, time: "12:30 PM", title: "Nile-view lunch",          description: "Relax at a curated local restaurant overlooking the Nile. Full meal included.",                   type: "meal",      duration: "1 hr" },
        { order: 6, time: "01:30 PM", title: "Egyptian Museum",          description: "Two dedicated hours with your guide through 120,000 artefacts — including Tutankhamun's gold mask.", type: "activity", duration: "2 hrs",   location: "Tahrir Square, Cairo" },
        { order: 7, time: "03:30 PM", title: "Hotel drop-off",           description: "Private vehicle returns you to your hotel.",                                                       type: "transport", duration: "30 min" },
      ],
      meals_included: ["lunch"],
    },
  ],
  created_at: "2024-01-15T00:00:00Z", updated_at: "2025-11-01T00:00:00Z",
};

export const MOCK_TRANSFER: Transfer = {
  id: 4, slug: "cairo-airport-transfer", type: "transfer",
  title: "Cairo International Airport → City Centre Private Transfer",
  tagline: "Stress-free arrival — your driver is waiting the moment you land",
  description: "After a long flight, the last thing you want is to negotiate with taxi drivers or wait for a shuttle. Your professional, English-speaking driver will be in the arrivals hall with a name sign, help with your luggage, and whisk you to your hotel in a clean, air-conditioned vehicle. Flight tracking means he'll be there even if your flight is delayed.",
  cover_image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=85",
  gallery: [
    { id: 1, url: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200&q=80", alt_text: "Airport terminal",   type: "image", is_cover: true,  order: 0 },
    { id: 2, url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80",    alt_text: "Private vehicle",    type: "image", is_cover: false, order: 1 },
    { id: 3, url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",  alt_text: "Driver waiting",     type: "image", is_cover: false, order: 2 },
  ],
  location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
  categories: [],
  price: 22, price_currency: "USD", price_unit: "per_vehicle",
  rating: 4.8, review_count: 541,
  review_stats: { average: 4.8, total: 541, distribution: { 5: 420, 4: 80, 3: 28, 2: 9, 1: 4 } },
  duration_label: "45 min", duration_hours: 1,
  languages: ["English", "Arabic"],
  cancellation_policy: "free_cancellation", cancellation_hours: 2,
  instant_confirmation: true, pickup_included: true,
  is_featured: false, is_active: true,
  highlights: ["Meet & greet in arrivals hall", "Flight tracking — no waiting", "Air-conditioned private vehicle", "Complimentary bottled water", "Luggage assistance", "No hidden fees"],
  includes: ["Private vehicle", "Professional driver", "Name sign in arrivals", "Bottled water", "All tolls & parking"],
  excludes: ["Gratuities (optional)"],
  addons: [
    { id: 10, slug: "child-seat", name: "Child car seat", description: "Certified child safety seat (up to 18 kg)", price: 5, price_currency: "USD", price_unit: "fixed", is_required: false, category: "equipment" },
    { id: 11, slug: "wifi",       name: "Pocket Wi-Fi",  description: "Unlimited 4G pocket Wi-Fi for your stay (7 days)", price: 12, price_currency: "USD", price_unit: "fixed", is_required: false, category: "equipment" },
  ],
  pickup_location:  "Cairo International Airport (CAI) — Terminal 2 Arrivals",
  dropoff_location: "Your hotel — City Centre / Zamalek / Maadi",
  pickup_address:   "Terminal 2, Cairo International Airport, El Nozha, Cairo",
  dropoff_address:  "Any hotel in Cairo central districts",
  vehicle_type:     "standard_car",
  vehicle_model:    "Toyota Camry or similar",
  max_passengers:   3,
  max_luggage:      3,
  driver_name:      "Mohamed Ali",
  driver_avatar:    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  flight_tracking:  true,
  wait_time_minutes: 60,
  distance_km:      40,
  estimated_time:   "45 min",
  created_at: "2024-02-01T00:00:00Z", updated_at: "2025-10-15T00:00:00Z",
};

export const MOCK_EXPERIENCE: Experience = {
  id: 2, slug: "egyptian-cooking-class", type: "experience",
  title: "Egyptian Home Cooking & Food Tasting with a Local Family",
  tagline: "A feast, a friendship, and a memory you'll carry home",
  description: "Fatima has been cooking for her family of eight in her Old Cairo apartment for over thirty years. Now she opens her home — and her recipes — to curious travellers who want to taste Egypt from the inside.\n\nYou'll join her in the kitchen to make koshari (Egypt's beloved street-food staple), ful medames, and mahshi (stuffed vine leaves). You'll knead dough, argue cheerfully over the right amount of cumin, and sit down together for a meal that feels nothing like a tour.\n\nThis is not a cooking demonstration. You cook, you eat, you talk. Fatima speaks limited English — her daughter Nadia translates — and somehow, by the time you leave, it feels like you've known them for years.",
  cover_image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1600&q=85",
  gallery: [
    { id: 1, url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80", alt_text: "Cooking together",   type: "image", is_cover: true,  order: 0 },
    { id: 2, url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80", alt_text: "Egyptian dishes",    type: "image", is_cover: false, order: 1 },
    { id: 3, url: "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?w=800&q=80", alt_text: "Spice market",       type: "image", is_cover: false, order: 2 },
    { id: 4, url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80", alt_text: "Plated koshari",     type: "image", is_cover: false, order: 3 },
  ],
  location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
  categories: [{ id: 2, name: "Food & Drink", slug: "food-drink" }],
  price: 38, price_currency: "USD", price_unit: "per_person",
  rating: 5.0, review_count: 87,
  review_stats: { average: 5.0, total: 87, distribution: { 5: 87, 4: 0, 3: 0, 2: 0, 1: 0 } },
  duration_label: "4 hours", duration_hours: 4,
  languages: ["English", "Arabic"],
  max_group_size: 8, min_age: 8,
  cancellation_policy: "free_cancellation", cancellation_hours: 24,
  instant_confirmation: true, pickup_included: false,
  is_featured: true, is_active: true,
  highlights: ["Cook three authentic Egyptian dishes from scratch", "Eat together with Fatima's family", "Visit a local spice market first", "Take home the recipes", "Maximum 8 guests — intimate setting"],
  includes: ["All ingredients", "Full meal", "Egyptian tea & coffee", "Printed recipes to take home"],
  excludes: ["Transport to/from the home", "Alcoholic beverages"],
  addons: [
    { id: 20, slug: "spice-pack", name: "Egyptian spice collection", description: "A curated bag of the exact spices used — sourced from Khan el-Khalili", price: 18, price_currency: "USD", price_unit: "fixed", is_required: false, category: "food" },
  ],
  host: {
    id: 1, name: "Fatima Al-Rashid", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    bio: "I have been cooking my mother's recipes since I was seven years old. My kitchen is small but my table is always long. I believe that the best way to understand a country is through its food — and I want to share that with you.",
    languages: ["Arabic", "English (basic)"],
    since: "2019", verified: true, superhost: true,
    reviews_count: 87, response_rate: 98,
  },
  story: "Fatima grew up in the same apartment where she now hosts guests — a third-floor walk-up in the Coptic Cairo neighbourhood, where the streets smell of cardamom and fresh bread. Her mother taught her. Her daughters help now. The recipes have been in the family for four generations, never written down until Fatima started printing them for guests.",
  style: "cooking", setting: "indoor", skill_level: "all",
  what_to_bring: ["Comfortable clothes you don't mind getting flour on", "An appetite"],
  what_to_expect: ["A warm, informal home environment", "Hands-on cooking — not just watching", "A full, shared meal", "Lots of laughter (translator provided)"],
  created_at: "2024-03-10T00:00:00Z", updated_at: "2025-11-05T00:00:00Z",
};

export const MOCK_REVIEWS = [
  { id: 1, author_name: "Sarah Mitchell",  author_country: "United Kingdom", author_avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80", rating: 5, title: "The best day of our trip", body: "Ahmed was phenomenal — passionate, knowledgeable, and so personable. He knew exactly when to give us space and when to add context. Standing inside the pyramid and hearing the history told by someone who clearly loves it was extraordinary. The Nile lunch was a nice touch. Would book again in a heartbeat.", date: "2026-02-12", verified: true, helpful_count: 24 },
  { id: 2, author_name: "Thomas Brenner",  author_country: "Germany",        author_avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80", rating: 5, title: "Exceeded every expectation", body: "We were nervous about a private tour feeling 'touristy' but this was the opposite. Ahmed treated us like intelligent adults, debated theories with us, and took us to spots the group tours avoid. The Egyptian Museum portion alone was worth the full price. Flawless organisation.", date: "2026-01-28", verified: true, helpful_count: 18 },
  { id: 3, author_name: "Yuki Tanaka",     author_country: "Japan",          author_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80", rating: 5, title: "Perfect for families", body: "We had our 8-year-old with us and Ahmed was brilliant with her — explaining things at her level, making it into a treasure hunt. She still talks about the Sphinx. The pace was relaxed, never rushed. Hotel pickup was seamless.", date: "2026-03-03", verified: true, helpful_count: 11 },
  { id: 4, author_name: "Marco Rossi",     author_country: "Italy",          author_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80", rating: 4, title: "Wonderful experience, minor logistics", body: "The tour itself was superb — Ahmed is a star and the Egyptian Museum was incredible. Only minor issue: pickup was 15 minutes late due to traffic, which squeezed the museum time slightly. Nothing that would stop me recommending this unreservedly.", date: "2026-01-15", verified: true, helpful_count: 7 },
];
