import type { TripBase } from "@/types";

export const MOCK_TRIPS: TripBase[] = [
  {
    id: 1, slug: "pyramids-sphinx-full-day", type: "tour",
    title: "Pyramids, Sphinx & Egyptian Museum Full-Day Tour",
    tagline: "The ultimate Cairo classic",
    description: "Walk the Giza Plateau with a licensed Egyptologist, descend into a pyramid, meet the Sphinx up close, then explore 120,000 artefacts at the Egyptian Museum.",
    cover_image: "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80",
    gallery: [], location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
    categories: [], price: 49, price_currency: "USD", price_unit: "per_person", original_price: 65,
    rating: 4.9, review_count: 312, duration_label: "8 hours", duration_hours: 8,
    languages: ["en", "ar"], max_group_size: 12,
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: true, is_featured: true, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 2, slug: "egyptian-cooking-class", type: "experience",
    title: "Egyptian Home Cooking & Food Tasting with a Local Family",
    tagline: "A feast you won't forget",
    description: "Learn to cook koshari, ful medames and mahshi in a Cairene home.",
    cover_image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    gallery: [], location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
    categories: [], price: 38, price_currency: "USD", price_unit: "per_person",
    rating: 5.0, review_count: 87, duration_label: "4 hours", duration_hours: 4,
    languages: ["en", "ar"], max_group_size: 8,
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: false, is_featured: true, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 3, slug: "luxor-valley-of-kings", type: "tour",
    title: "Valley of the Kings, Karnak & Luxor Temple Day Tour",
    tagline: "Ancient Thebes in one day",
    description: "Visit the tomb of Tutankhamun, the colossal Karnak temple complex and riverside Luxor Temple at dusk.",
    cover_image: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
    gallery: [], location: { id: 2, name: "Luxor", slug: "luxor", country: "Egypt", country_code: "EG" },
    categories: [], price: 75, price_currency: "USD", price_unit: "per_person",
    rating: 4.8, review_count: 203, duration_label: "Full day", duration_hours: 10,
    languages: ["en", "ar", "de"], max_group_size: 14,
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: true, is_featured: true, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 4, slug: "cairo-airport-transfer", type: "transfer",
    title: "Cairo International Airport → City Centre Private Transfer",
    tagline: "Stress-free arrival",
    description: "Private, air-conditioned vehicle direct to your hotel — flight tracking included.",
    cover_image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80",
    gallery: [], location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
    categories: [], price: 22, price_currency: "USD", price_unit: "per_vehicle",
    rating: 4.8, review_count: 541, duration_label: "45 min", duration_hours: 1,
    languages: ["en", "ar"],
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: true, is_featured: false, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 5, slug: "nile-felucca-sunset", type: "experience",
    title: "Sunset Felucca Sail on the Nile with Tea & Snacks",
    tagline: "Magic on the water",
    description: "Drift along the Nile as the sun dips behind the desert hills. Traditional tea and snacks included.",
    cover_image: "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&q=80",
    gallery: [], location: { id: 3, name: "Aswan", slug: "aswan", country: "Egypt", country_code: "EG" },
    categories: [], price: 28, price_currency: "USD", price_unit: "per_person",
    rating: 4.9, review_count: 156, duration_label: "2 hours", duration_hours: 2,
    languages: ["en", "ar"], max_group_size: 10,
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: false, is_featured: true, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 6, slug: "abu-simbel-day-trip", type: "tour",
    title: "Abu Simbel Temples Day Trip from Aswan by Flight",
    tagline: "Ramesses II awaits",
    description: "Fly to Abu Simbel and witness the most dramatic twin temples in Egypt.",
    cover_image: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&q=80",
    gallery: [], location: { id: 3, name: "Aswan", slug: "aswan", country: "Egypt", country_code: "EG" },
    categories: [], price: 185, price_currency: "USD", price_unit: "per_person",
    rating: 4.9, review_count: 94, duration_label: "Full day", duration_hours: 9,
    languages: ["en", "ar"], max_group_size: 12,
    cancellation_policy: "partial_refund", instant_confirmation: false,
    pickup_included: true, is_featured: true, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 7, slug: "cairo-night-transfer", type: "transfer",
    title: "Cairo City Centre → Cairo Airport Night Transfer",
    tagline: "Never miss a flight",
    description: "Reliable late-night pickup with professional driver and luggage assistance.",
    cover_image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80",
    gallery: [], location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
    categories: [], price: 22, price_currency: "USD", price_unit: "per_vehicle",
    rating: 4.7, review_count: 289, duration_label: "50 min", duration_hours: 1,
    languages: ["en", "ar"],
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: true, is_featured: false, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 8, slug: "khan-el-khalili-walk", type: "experience",
    title: "Khan el-Khalili Bazaar Night Walk & Mint Tea",
    tagline: "Cairo's medieval heart",
    description: "Wind through the labyrinthine medieval souq, meet artisans and sip mint tea at the oldest café in the world.",
    cover_image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
    gallery: [], location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
    categories: [], price: 32, price_currency: "USD", price_unit: "per_person",
    rating: 4.8, review_count: 124, duration_label: "3 hours", duration_hours: 3,
    languages: ["en", "ar"], max_group_size: 10,
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: false, is_featured: false, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 9, slug: "dahab-snorkel-day", type: "tour",
    title: "Dahab Blue Hole Snorkelling & Canyon Adventure",
    tagline: "Red Sea magic",
    description: "Snorkel the world-famous Blue Hole reef, then explore the canyon and lagoon with a certified instructor.",
    cover_image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    gallery: [], location: { id: 4, name: "Sinai", slug: "sinai", country: "Egypt", country_code: "EG" },
    categories: [], price: 55, price_currency: "USD", price_unit: "per_person",
    rating: 4.7, review_count: 67, duration_label: "6 hours", duration_hours: 6,
    languages: ["en", "ar"], max_group_size: 8,
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: true, is_featured: false, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 10, slug: "luxor-hotel-transfer", type: "transfer",
    title: "Luxor Airport → East Bank Hotel Private Transfer",
    tagline: "Arrive in style",
    description: "Climate-controlled private car from Luxor Airport to any East Bank hotel.",
    cover_image: "https://images.unsplash.com/photo-1485463611174-f302f6a5c1c9?w=800&q=80",
    gallery: [], location: { id: 2, name: "Luxor", slug: "luxor", country: "Egypt", country_code: "EG" },
    categories: [], price: 18, price_currency: "USD", price_unit: "per_vehicle",
    rating: 4.9, review_count: 198, duration_label: "25 min", duration_hours: 1,
    languages: ["en", "ar"],
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: true, is_featured: false, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 11, slug: "calligraphy-workshop-cairo", type: "experience",
    title: "Arabic Calligraphy Workshop in Old Cairo",
    tagline: "Write your name in history",
    description: "A master calligrapher teaches you the art of Arabic script in a 500-year-old caravanserai.",
    cover_image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
    gallery: [], location: { id: 1, name: "Cairo", slug: "cairo", country: "Egypt", country_code: "EG" },
    categories: [], price: 45, price_currency: "USD", price_unit: "per_person",
    rating: 4.9, review_count: 43, duration_label: "2.5 hours", duration_hours: 3,
    languages: ["en", "ar"], max_group_size: 6,
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: false, is_featured: false, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
  {
    id: 12, slug: "alexandria-day-trip", type: "tour",
    title: "Alexandria Day Trip — Library, Catacombs & Qaitbay",
    tagline: "Pearl of the Mediterranean",
    description: "Journey to Alexandria: visit the Bibliotheca Alexandrina, the Catacombs of Kom el Shoqafa, and the 15th-century Qaitbay Citadel on the sea.",
    cover_image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    gallery: [], location: { id: 5, name: "Alexandria", slug: "alexandria", country: "Egypt", country_code: "EG" },
    categories: [], price: 89, price_currency: "USD", price_unit: "per_person",
    rating: 4.7, review_count: 118, duration_label: "Full day", duration_hours: 11,
    languages: ["en", "ar"], max_group_size: 14,
    cancellation_policy: "free_cancellation", instant_confirmation: true,
    pickup_included: true, is_featured: false, is_active: true,
    highlights: [], includes: [], excludes: [], created_at: "", updated_at: "",
  },
];
