# Generated by Django 5.2.14 on 2026-05-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(default='Egypt', max_length=100)),
                ('country_code', models.CharField(default='EG', max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('avatar', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('trip_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('tour', 'Tour'), ('transfer', 'Transfer'), ('experience', 'Experience'), ('addon', 'Addon')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('price_unit', models.CharField(choices=[('per_person', 'Per Person'), ('per_group', 'Per Group'), ('per_vehicle', 'Per Vehicle'), ('fixed', 'Fixed')], default='per_person', max_length=20)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_label', models.CharField(max_length=50)),
                ('languages', models.JSONField(default=list)),
                ('max_group_size', models.PositiveIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('cancellation_policy', models.CharField(choices=[('free_cancellation', 'Free Cancellation'), ('partial_refund', 'Partial Refund'), ('non_refundable', 'Non-Refundable')], default='free_cancellation', max_length=30)),
                ('cancellation_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('instant_confirmation', models.BooleanField(default=True)),
                ('pickup_included', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('highlights', models.JSONField(default=list)),
                ('includes', models.JSONField(default=list)),
                ('excludes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='trips.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.location')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_avatar', models.URLField(blank=True)),
                ('author_country', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('images', models.JSONField(default=list)),
                ('response_body', models.TextField(blank=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_author', models.CharField(blank=True, max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.trip')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt_text', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('price_unit', models.CharField(choices=[('per_person', 'Per Person'), ('per_group', 'Per Group'), ('fixed', 'Fixed')], default='per_person', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('transport', 'Transport'), ('food', 'Food'), ('equipment', 'Equipment'), ('guide', 'Guide'), ('insurance', 'Insurance'), ('photo', 'Photo/Video'), ('other', 'Other')], max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='trips.trip')),
            ],
        ),
    ]
