# Generated by Django 5.2.14 on 2026-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='best_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='climate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='currency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='highlights',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='location',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
