# Generated by Django 5.2.14 on 2026-05-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_booking_bookingaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cover_image_file',
            field=models.ImageField(blank=True, upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='location',
            name='hero_image_file',
            field=models.ImageField(blank=True, upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cover_image_file',
            field=models.ImageField(blank=True, upload_to='trips/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
    ]
